#!/usr/bin/env bash
# Configure your domain zone

display_info () {
	dig "$2.$1" | awk '/;; ANSWER SECTION/ {getline;
	printf "The subdomain %s is a %s record and points to %s\n", dom, $4, $5}' dom="$2"
}

if [ $# -gt 1 ]
then
	display_info "$1" "$2"
else
	display_info "$1" "www"
	display_info "$1" "lb-01"
	display_info "$1" "web-01"
	display_info "$1" "web-02"
fi