#!/usr/bin/env bash
# Installs NGINX web server on web-01

sudo apt update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.html
sed -i '24 i \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4i permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
