#!/usr/bin/env bash
#  configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i '46 i add_header X-Served-By-$HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
