#!/usr/bin/env bash
# Configured nginx to work on port 80

sudo apt-get update
sudo apt-get -y upgrade
sudo sed -i "22 i listen 80 default_server" /etc/nginx/sites-enabled/default
sudo service nginx restart