#!/usr/bin/env bash
# Run Nginx as Nginx

chown nginx:nginx /etx/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
